/* eslint-disable @typescript-eslint/no-deprecated -- tseslint.config() is the only way to use extends; core defineConfig has incompatible API */
import { includeIgnoreFile } from "@eslint/config-helpers";
import eslint from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import eslintPluginAstro from "eslint-plugin-astro";
import pluginReact from "eslint-plugin-react";
import reactCompiler from "eslint-plugin-react-compiler";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import path from "node:path";
import tseslint from "typescript-eslint";

const gitignorePath = path.resolve(import.meta.dirname, ".gitignore");

const baseConfig = tseslint.config({
  extends: [eslint.configs.recommended, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
  languageOptions: {
    parserOptions: {
      projectService: true,
      tsconfigRootDir: import.meta.dirname,
    },
  },
  rules: {
    "no-console": "warn",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
    "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
  },
});

const reactConfig = tseslint.config({
  files: ["**/*.{js,jsx,ts,tsx}"],
  extends: [pluginReact.configs.flat.recommended],
  languageOptions: {
    ...pluginReact.configs.flat.recommended.languageOptions,
    globals: {
      window: true,
      document: true,
    },
  },
  plugins: {
    "react-hooks": eslintPluginReactHooks,
    "react-compiler": reactCompiler,
  },
  settings: { react: { version: "detect" } },
  rules: {
    ...eslintPluginReactHooks.configs.recommended.rules,
    "react/react-in-jsx-scope": "off",
    "react-compiler/react-compiler": "error",
  },
});

const astroConfig = tseslint.config({
  files: ["**/*.astro"],
  rules: {
    "astro/no-set-html-directive": "error",
    "astro/no-unused-css-selector": "warn",
    "astro/prefer-class-list-directive": "warn",
  },
});

export default tseslint.config(
  includeIgnoreFile(gitignorePath),
  // src/db/database.types.ts is generated by `npm run db:types` and must stay byte-identical to
  // the generator's output — linting it (and worse, `eslint --fix` via lint-staged) would rewrite
  // it and make regeneration produce a diff. Fix the schema, never the generated file.
  { ignores: ["src/db/database.types.ts"] },
  baseConfig,
  // Ops scripts are plain Node, outside the TypeScript project this config type-checks against.
  // They are NOT exempt from linting — scripts/supabase-db.mjs is the one file that handles
  // database passwords and spawns processes against production, so it is the last place to drop
  // coverage. Only the type-aware rules are dropped, because there are no types to check against.
  {
    files: ["scripts/**"],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      parserOptions: { projectService: false, project: false },
      // Declared explicitly rather than pulling in a whole `globals.node` set: what these scripts
      // are allowed to reach is part of what they are. `fetch` and `setTimeout` are the readiness
      // probe in `e2e-serve.mjs`.
      globals: {
        console: "readonly",
        process: "readonly",
        URL: "readonly",
        // The post-deploy smoke posts a form body: the sign-in endpoint reads `formData()`, not
        // JSON, so the probe has to encode the same way a browser does (`deploy-smoke.mjs`).
        URLSearchParams: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: {
      // An ops script's output is its interface.
      "no-console": "off",
    },
  },
  reactConfig,
  eslintPluginAstro.configs["flat/recommended"],
  ...eslintPluginAstro.configs["flat/jsx-a11y-recommended"],
  astroConfig,
  eslintPluginPrettier,
);
