import { useEffect, useState } from "react";
import { Pencil, Trash2, Trophy } from "lucide-react";
import type {
  EstimationFormula,
  Exercise,
  ExerciseEntryView,
  LoggedSetView,
  RecordAnnouncement,
  WeightUnit,
} from "@/types";
import { bestEstimateOf, estimateForLoggedSet, roundForDisplay } from "@/lib/services/set-display";
import type { SetEstimate } from "@/lib/services/set-estimate";
import { workoutMessageForCode } from "@/lib/validation/workout";
import { MUSCLE_GROUP_LABELS } from "@/lib/validation/exercise";
import { useRecordImpact } from "@/components/hooks/useRecordImpact";
import { AddSetForm } from "@/components/workouts/AddSetForm";
import { EditSetForm } from "@/components/workouts/EditSetForm";
import { ExercisePicker } from "@/components/workouts/ExercisePicker";
import { RecordImpactDialog } from "@/components/workouts/RecordImpactDialog";

// Holds the workout in state and appends to it, so a lifter logging six sets between efforts never
// waits for a page load. Every write is still a real write — nothing is buffered here for later.
//
// Since S-05 the state also REPLACES and REMOVES, and both go through the row the server answered
// with rather than through the values typed here — `weight_kg` is generated by the database and must
// never be guessed client-side, and the entry's best estimate then recomputes from the array by
// itself, with no extra request.

/** What the confirmation dialog is currently guarding, and everything the confirm needs to act. */
type Confirming =
  | { kind: "delete-set"; entryId: string; setId: string }
  | { kind: "delete-entry"; entryId: string; exerciseName: string }
  | { kind: "edit-set"; entryId: string; setId: string; fields: EditableSetFields };

interface EditableSetFields {
  reps: number;
  weight: number;
  rpe: number | null;
}

interface Props {
  workoutId: string;
  initialEntries: ExerciseEntryView[];
  catalogue: Exercise[];
  weightUnit: WeightUnit;
  estimationFormula: EstimationFormula;
}

export default function WorkoutDetail({ workoutId, initialEntries, catalogue, weightUnit, estimationFormula }: Props) {
  const [entries, setEntries] = useState(initialEntries);
  const [pickerError, setPickerError] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  // An object rather than a bare id: choosing the same exercise twice must scroll to it twice, and
  // an unchanged id would not re-run the effect below.
  const [focusRequest, setFocusRequest] = useState<{ entryId: string } | null>(null);
  // Record announcements, keyed by the set that earned one.
  //
  // **Deliberately not read back from the server on load** (PRD: "the save-time flag is ephemeral
  // and only covers the set just logged, while the list is what the user checks"). So this state is
  // seeded empty and only ever gains entries from a save in this session: after a reload the badges
  // are gone and `/records` is where the record lives. Keeping them would also mean inventing
  // behaviour for what happens when S-05 lets a set be edited out from under one.
  //
  // A `Map` rather than an object: `.get()` returns `RecordAnnouncement | undefined`, which is the
  // truth, whereas indexing a `Record<string, T>` is typed as always present because this project
  // does not enable `noUncheckedIndexedAccess` — and a guard against that reads to the type-checked
  // lint rule as dead code.
  const [records, setRecords] = useState(() => new Map<string, RecordAnnouncement>());
  // Which set is showing its inline edit form, and what the dialog is guarding right now.
  const [editingSetId, setEditingSetId] = useState<string | null>(null);
  const [confirming, setConfirming] = useState<Confirming | null>(null);
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const impact = useRecordImpact();

  useEffect(() => {
    if (!focusRequest) {
      return;
    }
    // Runs after the render that added the entry, so the element is in the document by now.
    document.getElementById(`entry-${focusRequest.entryId}`)?.scrollIntoView({ behavior: "smooth", block: "start" });
  }, [focusRequest]);

  async function handlePick(exercise: Exercise) {
    setPickerError(null);

    const present = entries.find((entry) => entry.exercise_id === exercise.id);
    if (present) {
      // The visible half of the idempotent-entry decision: an exercise already in this workout is
      // not an error, it is somewhere to go.
      setFocusRequest({ entryId: present.id });
      return;
    }

    setAdding(true);
    try {
      const response = await fetch("/api/exercise-entries", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ workoutId, exerciseId: exercise.id }),
      });
      const body: unknown = await response.json();

      if (!response.ok) {
        setPickerError(workoutMessageForCode((body as { code?: string }).code));
        return;
      }

      const { entry, created } = body as { entry: { id: string; exercise_id: string }; created: boolean };

      if (created) {
        setEntries((current) => [
          ...current,
          {
            id: entry.id,
            exercise_id: entry.exercise_id,
            exercises: {
              id: exercise.id,
              name: exercise.name,
              muscle_group: exercise.muscle_group,
              is_bodyweight: exercise.is_bodyweight,
            },
            sets: [],
          },
        ]);
      }
      setFocusRequest({ entryId: entry.id });
    } catch {
      setPickerError(workoutMessageForCode("unexpected"));
    } finally {
      setAdding(false);
    }
  }

  function handleLogged(entryId: string, set: LoggedSetView, record: RecordAnnouncement | null) {
    setEntries((current) =>
      current.map((entry) => (entry.id === entryId ? { ...entry, sets: [...entry.sets, set] } : entry)),
    );
    if (record) {
      setRecords((current) => new Map(current).set(set.id, record));
    }
  }

  /**
   * Drop the save-time badge for a set that has just been changed or removed.
   *
   * The badge asserts "this set beat your record". After an edit that sentence may simply be false,
   * and after a delete the set it points at is gone — a false badge is the same class of defect as a
   * placeholder number: technically explicable, and a lie to a human. `/records` is the durable
   * surface and stays correct on its own, because nothing about a record is stored.
   */
  function forgetBadges(setIds: readonly string[]) {
    setRecords((current) => {
      const next = new Map(current);
      for (const id of setIds) {
        next.delete(id);
      }
      return next;
    });
  }

  function closeDialog() {
    setConfirming(null);
    setActionError(null);
    impact.clear();
  }

  function askDeleteSet(entryId: string, setId: string) {
    setActionError(null);
    setConfirming({ kind: "delete-set", entryId, setId });
    // The dialog opens on "loading" and fills in — the read happens when it opens and never at page
    // load, because sets get logged throughout a session and a stale figure is worse than an absent
    // one for a number somebody is about to act on.
    void impact.load(`/api/sets/${setId}/impact`);
  }

  function askDeleteEntry(entryId: string, exerciseName: string) {
    setActionError(null);
    setConfirming({ kind: "delete-entry", entryId, exerciseName });
    void impact.load(`/api/exercise-entries/${entryId}/impact`);
  }

  /**
   * An edit asks first only when there is something to ask about.
   *
   * A deletion is irreversible whether or not a record depends on it, so it always confirms. An edit
   * is not: correcting a mistyped RPE on a set nothing depends on should cost one tap, and a dialog
   * that always says "no record depends on this" teaches people to click through the one that
   * matters. So the preflight runs first, and the dialog appears only when a record is at stake — or
   * when the preflight could not say, which is emphatically not the same as "nothing is".
   */
  async function submitSetEdit(entryId: string, setId: string, fields: EditableSetFields) {
    setActionError(null);
    setBusy(true);
    try {
      const state = await impact.load(`/api/sets/${setId}/impact`);
      if (state.kind === "ready" && state.impact.length === 0) {
        await applySetEdit(entryId, setId, fields);
        impact.clear();
        return;
      }
      setConfirming({ kind: "edit-set", entryId, setId, fields });
    } finally {
      setBusy(false);
    }
  }

  /** Answers whether the write landed, so the caller knows whether to close what it opened. */
  async function applySetEdit(entryId: string, setId: string, fields: EditableSetFields): Promise<boolean> {
    try {
      const response = await fetch(`/api/sets/${setId}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(fields),
      });
      const body: unknown = await response.json();

      if (!response.ok) {
        setActionError(workoutMessageForCode((body as { code?: string }).code));
        return false;
      }

      const { set } = body as { set: LoggedSetView };
      setEntries((current) =>
        current.map((entry) =>
          entry.id === entryId
            ? { ...entry, sets: entry.sets.map((existing) => (existing.id === set.id ? set : existing)) }
            : entry,
        ),
      );
      forgetBadges([setId]);
      setEditingSetId(null);
      return true;
    } catch {
      setActionError(workoutMessageForCode("unexpected"));
      return false;
    }
  }

  async function applyDelete(url: string, onDeleted: () => void): Promise<boolean> {
    try {
      const response = await fetch(url, { method: "DELETE" });

      if (!response.ok) {
        // 404 here is the zero-rows rule doing its job: the row is absent or not this account's,
        // and either way the screen must not pretend something was removed.
        const body: unknown = await response.json();
        setActionError(workoutMessageForCode((body as { code?: string }).code));
        return false;
      }

      onDeleted();
      return true;
    } catch {
      setActionError(workoutMessageForCode("unexpected"));
      return false;
    }
  }

  async function handleConfirm() {
    if (!confirming) {
      return;
    }

    setBusy(true);
    setActionError(null);
    try {
      const done = await runConfirmed(confirming);
      if (done) {
        closeDialog();
      }
    } finally {
      setBusy(false);
    }
  }

  function runConfirmed(action: Confirming): Promise<boolean> {
    switch (action.kind) {
      case "edit-set":
        return applySetEdit(action.entryId, action.setId, action.fields);

      case "delete-set":
        return applyDelete(`/api/sets/${action.setId}`, () => {
          setEntries((current) =>
            current.map((entry) =>
              entry.id === action.entryId
                ? { ...entry, sets: entry.sets.filter((set) => set.id !== action.setId) }
                : entry,
            ),
          );
          forgetBadges([action.setId]);
          setEditingSetId((current) => (current === action.setId ? null : current));
        });

      case "delete-entry":
        return applyDelete(`/api/exercise-entries/${action.entryId}`, () => {
          const removed = entries.find((entry) => entry.id === action.entryId);
          setEntries((current) => current.filter((entry) => entry.id !== action.entryId));
          forgetBadges(removed ? removed.sets.map((set) => set.id) : []);
        });
    }
  }

  return (
    <div className="space-y-6">
      <ExercisePicker
        catalogue={catalogue}
        presentExerciseIds={entries.map((entry) => entry.exercise_id)}
        onPick={(exercise) => {
          void handlePick(exercise);
        }}
        pending={adding}
        error={pickerError}
      />

      {entries.length === 0 ? (
        <p className="rounded-lg border border-white/10 bg-white/5 px-4 py-8 text-center text-blue-100/60">
          No exercises in this workout yet. Pick one above and log your first set.
        </p>
      ) : (
        <ul className="space-y-4">
          {entries.map((entry) => {
            const best = bestEstimateOf(entry.sets, weightUnit, estimationFormula);
            return (
              <li
                key={entry.id}
                id={`entry-${entry.id}`}
                className="scroll-mt-4 overflow-hidden rounded-lg border border-white/10 bg-white/5"
              >
                <header className="flex flex-wrap items-baseline justify-between gap-2 px-4 py-3">
                  <h2 className="font-medium text-white">{entry.exercises.name}</h2>
                  <span className="flex items-center gap-2 text-xs">
                    {entry.exercises.is_bodyweight && (
                      <span className="rounded-full bg-blue-500/20 px-2 py-0.5 text-blue-200">bodyweight</span>
                    )}
                    <span className="text-blue-100/50">{MUSCLE_GROUP_LABELS[entry.exercises.muscle_group]}</span>
                    <button
                      type="button"
                      aria-label={`Remove ${entry.exercises.name} from this workout`}
                      onClick={() => {
                        askDeleteEntry(entry.id, entry.exercises.name);
                      }}
                      className="flex items-center gap-1 rounded-lg border border-red-400/40 px-2 py-1 text-red-200 transition-colors hover:bg-red-500/15"
                    >
                      <Trash2 className="size-3.5" />
                      Remove
                    </button>
                  </span>
                </header>

                {best !== null && (
                  // FR-015: the best estimate among this entry's own sets, not a stored trophy —
                  // it is recomputed from whatever sets are here, so it can go down as well as up.
                  <p className="flex items-center gap-2 border-t border-white/10 px-4 py-2 text-sm text-amber-200">
                    <Trophy className="size-4 shrink-0" />
                    Best estimated 1RM here: <strong>{roundForDisplay(best)}</strong> {weightUnit}
                  </p>
                )}

                {entry.sets.length === 0 ? (
                  // Deleting the last set must leave a screen that explains itself rather than an
                  // empty box — and the exercise stays removable from here, which is the whole
                  // reason entry deletion exists.
                  <p className="border-t border-white/10 px-4 py-3 text-sm text-blue-100/50">
                    No sets logged for this exercise yet.
                  </p>
                ) : (
                  <ol className="divide-y divide-white/5 border-t border-white/10">
                    {entry.sets.map((set, index) => {
                      const announcement = records.get(set.id);
                      return (
                        <li key={set.id} className="px-4 py-2">
                          <div className="flex flex-wrap items-baseline justify-between gap-2">
                            <span className="text-white">
                              <span className="mr-2 text-xs text-blue-100/40">#{index + 1}</span>
                              {set.reps} × {set.weight} {set.weight_unit}
                              {set.rpe !== null && <span className="ml-2 text-xs text-blue-100/50">RPE {set.rpe}</span>}
                            </span>
                            <span className="flex items-center gap-3">
                              <SetEstimateLabel
                                estimate={estimateForLoggedSet(set, weightUnit, estimationFormula)}
                                unit={weightUnit}
                              />
                              <span className="flex items-center gap-1">
                                <button
                                  type="button"
                                  aria-label={`Edit set ${index + 1} of ${entry.exercises.name}`}
                                  onClick={() => {
                                    setActionError(null);
                                    setEditingSetId((current) => (current === set.id ? null : set.id));
                                  }}
                                  className="rounded-lg border border-white/15 p-1.5 text-blue-100/70 transition-colors hover:bg-white/10 hover:text-white"
                                >
                                  <Pencil className="size-3.5" />
                                </button>
                                <button
                                  type="button"
                                  aria-label={`Delete set ${index + 1} of ${entry.exercises.name}`}
                                  onClick={() => {
                                    askDeleteSet(entry.id, set.id);
                                  }}
                                  className="rounded-lg border border-red-400/40 p-1.5 text-red-200 transition-colors hover:bg-red-500/15"
                                >
                                  <Trash2 className="size-3.5" />
                                </button>
                              </span>
                            </span>
                          </div>
                          {announcement && (
                            // Its own line rather than a third item in the row above: at 360 px the
                            // row already wraps, and a record is the one thing here that must not
                            // arrive looking like an afterthought squeezed between two numbers.
                            <RecordBadge announcement={announcement} unit={weightUnit} formula={estimationFormula} />
                          )}
                          {editingSetId === set.id && (
                            <EditSetForm
                              set={set}
                              isBodyweight={entry.exercises.is_bodyweight}
                              pending={busy}
                              // Only while no dialog is open: with one up, the failure belongs there,
                              // beside the control that would retry it.
                              error={confirming ? null : actionError}
                              onSubmit={(fields) => {
                                void submitSetEdit(entry.id, set.id, fields);
                              }}
                              onCancel={() => {
                                setEditingSetId(null);
                                setActionError(null);
                              }}
                            />
                          )}
                        </li>
                      );
                    })}
                  </ol>
                )}

                <AddSetForm
                  entryId={entry.id}
                  isBodyweight={entry.exercises.is_bodyweight}
                  weightUnit={weightUnit}
                  onLogged={(set, record) => {
                    handleLogged(entry.id, set, record);
                  }}
                />
              </li>
            );
          })}
        </ul>
      )}

      {/* One dialog for all three of this island's operations, so the sentence a user reads before
          an irreversible action is written in exactly one place. */}
      <RecordImpactDialog
        open={confirming !== null}
        action={confirming?.kind === "edit-set" ? "edit" : "delete"}
        title={dialogTitle(confirming)}
        consequence={dialogConsequence(confirming)}
        confirmLabel={confirming?.kind === "edit-set" ? "Save changes" : "Delete"}
        state={impact.state ?? { kind: "loading" }}
        unit={weightUnit}
        formula={estimationFormula}
        pending={busy}
        error={actionError}
        onConfirm={() => {
          void handleConfirm();
        }}
        onCancel={closeDialog}
      />
    </div>
  );
}

/**
 * The dialog's own words, kept out of the render body.
 *
 * `null` is reachable only on the frame where the dialog is closing, so the strings below are never
 * read on screen — the alternative is a conditional render that would unmount the dialog mid-close
 * and lose the browser's focus restoration.
 */
function dialogTitle(confirming: Confirming | null): string {
  switch (confirming?.kind) {
    case "edit-set":
      return "Save this change?";
    case "delete-entry":
      return "Remove this exercise?";
    default:
      return "Delete this set?";
  }
}

function dialogConsequence(confirming: Confirming | null): string {
  switch (confirming?.kind) {
    case "edit-set":
      return "This replaces what you logged for this set.";
    case "delete-entry":
      return `This removes ${confirming.exerciseName} from this workout, with every set logged under it. It cannot be undone.`;
    default:
      return "This removes the set from this workout. It cannot be undone.";
  }
}

/**
 * "You just beat your best" — the one thing this product exists to say at the moment it happens.
 *
 * **Both numbers on this line are re-derived in TypeScript.** The set's own estimate comes from the
 * estimator above; what it beat is computed here from the previous best set's typed weight, through
 * the same `estimateForLoggedSet`. The verdict came from SQL, but no number SQL computed is
 * rendered — which is what keeps the badge and the workout row from ever disagreeing by a digit.
 *
 * The previous best is estimable by construction (it came out of a ranking that excludes everything
 * unestimable), so the guard below is unreachable in practice. It is written rather than asserted
 * because the alternative is a non-null assertion that would be wrong exactly once.
 */
function RecordBadge({
  announcement,
  unit,
  formula,
}: {
  announcement: RecordAnnouncement;
  unit: WeightUnit;
  formula: EstimationFormula;
}) {
  const previous = estimateForLoggedSet(announcement.previousBest, unit, formula);

  return (
    <p className="mt-1.5 flex flex-wrap items-center gap-1.5 text-xs font-medium text-amber-300">
      <Trophy className="size-3.5 shrink-0" />
      Personal record
      {previous.kind === "estimate" && (
        <span className="font-normal text-amber-200/80">
          — beat {roundForDisplay(previous.oneRepMax)} {unit}
        </span>
      )}
    </p>
  );
}

/**
 * What a set is worth — or, in three cases out of four, why there is no number.
 *
 * Showing nothing would teach the user nothing. "Outside 1–12 reps" says the product is declining
 * to guess rather than failing, which is the difference between a limit and a bug.
 */
function SetEstimateLabel({ estimate, unit }: { estimate: SetEstimate; unit: WeightUnit }) {
  if (estimate.kind === "estimate") {
    return (
      <span className="text-sm text-purple-200">
        ≈ <strong>{roundForDisplay(estimate.oneRepMax)}</strong> {unit} 1RM
      </span>
    );
  }

  const phrase =
    estimate.kind === "bodyweight"
      ? "bodyweight — no load to estimate from"
      : estimate.kind === "assisted"
        ? "assisted — no estimate"
        : "outside 1–12 reps — no estimate";

  return <span className="text-sm text-blue-100/50">{phrase}</span>;
}
