// Shared entity and DTO types.
//
// Everything here is *derived* from the generated schema types in `@/db/database.types` — never
// restated by hand. A hand-copied field list that drifts from the schema is worse than no type at
// all: it type-checks while describing a table that no longer exists in that shape.

import type { Database } from "@/db/database.types";
import type { EstimationFormula as ServiceEstimationFormula } from "@/lib/services/one-rep-max";

/** One row per authenticated account, holding the preferences every derived number depends on. */
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type ProfileInsert = Database["public"]["Tables"]["profiles"]["Insert"];
export type ProfileUpdate = Database["public"]["Tables"]["profiles"]["Update"];

/**
 * A catalogue entry. `user_id === null` marks a seeded row every account reads and none may write;
 * a non-null `user_id` marks a custom exercise private to that account.
 */
export type Exercise = Database["public"]["Tables"]["exercises"]["Row"];
export type ExerciseInsert = Database["public"]["Tables"]["exercises"]["Insert"];
export type ExerciseUpdate = Database["public"]["Tables"]["exercises"]["Update"];

/** The one primary muscle group every exercise carries (FR-013). Exactly six, closed set. */
export type MuscleGroup = Database["public"]["Enums"]["muscle_group"];

/**
 * The same six, as a value — the UI needs to iterate them for a filter and a select, and a
 * hand-written list in a component is how a seventh group ships to the database and never reaches
 * the screen. Order matches the enum's declaration order, which is what any `order by` will use.
 */
export const MUSCLE_GROUPS = ["legs", "back", "chest", "shoulders", "arms", "core"] as const;

/**
 * One training session: a date the user stated, an optional note, and the exercise entries under
 * it. `performed_on` is a calendar date rather than an instant, so changing the profile timezone
 * later cannot move a workout to a different day.
 */
export type Workout = Database["public"]["Tables"]["workouts"]["Row"];
export type WorkoutInsert = Database["public"]["Tables"]["workouts"]["Insert"];
export type WorkoutUpdate = Database["public"]["Tables"]["workouts"]["Update"];

/**
 * One exercise within one workout — the middle level the PRD calls an "exercise entry" (US-04).
 * At most one per exercise per workout: choosing an exercise already present adds a set to the
 * entry that is there. Carries `exercise_id` and nothing copied from the exercise, so a later
 * correction to a muscle group applies to history.
 */
export type ExerciseEntry = Database["public"]["Tables"]["exercise_entries"]["Row"];
export type ExerciseEntryInsert = Database["public"]["Tables"]["exercise_entries"]["Insert"];
export type ExerciseEntryUpdate = Database["public"]["Tables"]["exercise_entries"]["Update"];

/**
 * One set: repetitions against a load. Named `WorkoutSet` rather than `Set` on purpose — `Set`
 * shadows the built-in and sends the next reader of a type error looking in the wrong place.
 *
 * `weight` is what the user typed and `weight_unit` is what they typed it in; `weight_kg` is
 * generated by the database from both. **Never write `weight_kg`** — Postgres refuses a non-DEFAULT
 * value for a generated column, and the generated types cannot express that, so they list it as an
 * optional field on Insert. Read it for every comparison and every total; read `weight` for
 * anything shown back to the user.
 */
export type WorkoutSet = Database["public"]["Tables"]["sets"]["Row"];
export type WorkoutSetInsert = Database["public"]["Tables"]["sets"]["Insert"];
export type WorkoutSetUpdate = Database["public"]["Tables"]["sets"]["Update"];

// The shapes the workout screens are handed. They exist because a hydrated island may not import
// `@/lib/services/workouts` — that module pulls in the Supabase client, and everything reachable
// from a `client:load` component ships to the browser. Each is PICKED from the row type rather than
// restated, so a column that changes shape breaks the page instead of drifting from it.

/** One set as the workout screen reads it: what was typed, its unit, and the canonical value. */
export type LoggedSetView = Pick<WorkoutSet, "id" | "reps" | "weight" | "weight_unit" | "weight_kg" | "rpe">;

/** The little the screen needs about the exercise an entry points at. */
export type EntryExerciseView = Pick<Exercise, "id" | "name" | "muscle_group" | "is_bodyweight">;

/** One exercise within one workout, with its sets in the order they were logged. */
export type ExerciseEntryView = Pick<ExerciseEntry, "id" | "exercise_id"> & {
  exercises: EntryExerciseView;
  sets: LoggedSetView[];
};

/**
 * Unit weights are entered and displayed in. Storage keeps both: the value as entered alongside the
 * unit it was entered in, plus a generated canonical `sets.weight_kg` — which is what makes a
 * weight entered in pounds read back as the number typed, rather than as a rounding argument.
 */
export type WeightUnit = Database["public"]["Enums"]["weight_unit"];

/** Which formula estimates a one-rep max. Both are valid for 1–12 repetitions only. */
export type EstimationFormula = Database["public"]["Enums"]["estimation_formula"];

// `src/lib/services/one-rep-max.ts` declares the same union by hand, and must keep doing so:
// AGENTS.md requires the calculation module stay dependency-free so it remains directly
// unit-testable. The duplication is therefore deliberate — but nothing else would keep the two in
// step. Add a formula to the Postgres enum without teaching the estimator about it and this
// assertion stops compiling, instead of the new formula silently falling through to an existing
// branch and producing a number the user would believe.
// `false`, not `never`, on mismatch — and passed through a constraint. A bare alias resolving to
// `never` is not an error, only an unused declaration, so the first version of this check silently
// passed the very mutation it was written to catch.
type MutuallyAssignable<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Assert<T extends true> = T;
export type _EstimationFormulaUnionsAgree = Assert<MutuallyAssignable<EstimationFormula, ServiceEstimationFormula>>;

// The same guard for the muscle-group tuple above. Add a seventh value to the Postgres enum without
// adding it to MUSCLE_GROUPS and this stops compiling — instead of the new group existing in the
// database, being assignable to exercises through the API, and silently missing from every filter
// and select on screen. `false`, not `never`, for the reason spelled out above.
export type _MuscleGroupTupleCoversEnum = Assert<MutuallyAssignable<MuscleGroup, (typeof MUSCLE_GROUPS)[number]>>;
